### ISSUE TITLE
Dragon's Stand (HoT) locations

### ISSUE THREAD

**Issue by LadyElyssa** [agaertner/bhud-markers#1]
As the Treasure Mushroom seems to be your speciality, I thought you might find the locations useful in Dragon's Stand even though the Treasure Mushroom only spawns after the Meta there.

<POI MapID="1041" xpos="75.4249" ypos="59.4979" zpos="539.159" />
<POI MapID="1041" xpos="526.597" ypos="56.7126" zpos="-85.9149"/>
<POI MapID="1041" xpos="327.082" ypos="112.896" zpos="152.588"/>

**Comment by agaertner** [comment]
I rarely participate in the event nowadays and since those are done pretty fast by a group of people I've decided to exclude those. Besides, it makes it more difficult to let it walk by each hiding spot when they are being pulled as soon as they appear.
